$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
<<<<<<< HEAD
name: used-car-predict-train-env
=======

name: used-cars-train-env  # Provide the name for the environment
>>>>>>> 2628d14955839e928336111607b43bdd8334e880
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Environment created from a Docker image plus Conda environment to train Machine Failure Classification model
